# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171020_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 9, 39, 26, 521228, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
